### ISSUE TITLE
Installation/compilation instructions

### ISSUE THREAD

**Issue by nodiscc** [ZapBlasterson/crushpaper#2]
Hi, what is required to run crushpaper locally? https://github.com/ZapBlasterson/crushpaper/blob/master/doc/System-Overview.md#the-crushpaper-server mentions 

> This is a Java application. It is packaged as a single executable JAR file

however this repo only contains the java source. I am asking this because crushpaper has been mentioned at https://github.com/Kickball/awesome-selfhosted/issues/312 and we really would like to ensure that users are able to run this on their own server 

Thanks

**Comment by ZapBlasterson** [comment]
Hi,

You can download the jar here: https://github.com/ZapBlasterson/crushpaper/releases

This page explains how to create a start script for the jar https://github.com/ZapBlasterson/crushpaper/blob/master/doc/Build%2C-Install%2C-Configure-and-Run.md

**Comment by nodiscc** [comment]
Thank you. I had a quick look at the doc but missed this page.
Best of luck with this project, it looks quite nice; feel free to check and improve https://github.com/Kickball/awesome-selfhosted anytime

**Comment by Kickball** [comment]
Can a link to this installation information be added to readme.md?

**Comment by ZapBlasterson** [comment]
Sure, I just added it.

**Comment by Kickball** [comment]
Thanks, this will be added to [awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted) shortly.
